# Generated by Django 4.0.3 on 2022-04-03 01:21

import ckeditor.fields
from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, max_length=4096)),
                ('phone_number', models.CharField(max_length=16, null=True)),
                ('email', models.CharField(max_length=16, null=True)),
            ],
            options={
                'verbose_name': 'Люди подписавшие на новости',
                'verbose_name_plural': 'Люди подписавшие на новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=4096)),
                ('image', models.ImageField(blank=True, upload_to=news.models.collection_dir, verbose_name='Главное фото')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=4096)),
                ('image', models.ImageField(blank=True, upload_to='news', verbose_name='Главное фото')),
                ('active', models.BooleanField(default=True)),
                ('text', ckeditor.fields.RichTextField(verbose_name='Тест новости')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
                'ordering': ['-created_at'],
            },
        ),
    ]
