# Generated by Django 4.0.3 on 2022-05-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_thumb240',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='news/thumbs', verbose_name='Фото (240px)'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_thumb480',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='news/thumbs', verbose_name='Фото (480px)'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_thumb720',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='news/thumbs', verbose_name='Фото (720px)'),
        ),
    ]
