# Generated by Django 4.0.3 on 2022-05-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_image_thumb240_news_image_thumb480_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Видео'),
        ),
    ]
