# Generated by Django 4.0.3 on 2022-05-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcast',
            name='email',
        ),
        migrations.AlterField(
            model_name='news',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
