# Generated by Django 4.0.3 on 2022-05-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_broadcast_email_alter_news_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
