# Generated by Django 4.0.3 on 2022-05-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_collection_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='phone_number',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
