# Generated by Django 4.0.3 on 2022-04-02 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='color',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.color', verbose_name='Цвет в фото'),
            preserve_default=False,
        ),
    ]
