# Generated by Django 4.0.3 on 2022-04-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_image_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=100000, verbose_name='Цена'),
        ),
    ]
