# Generated by Django 4.0.3 on 2022-04-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_producttype_options_rename_type_size_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='type',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Одежда'), (1, 'Головные уборы'), (2, 'Обувь')], default=0, verbose_name='Тип размера'),
        ),
        migrations.AlterField(
            model_name='size',
            name='gender',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Женский'), (1, 'Мужской')], verbose_name='Пол'),
        ),
    ]
