# Generated by Django 4.0.3 on 2022-04-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_productavailability_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='set_colors',
            field=models.ManyToManyField(blank=True, null=True, to='shop.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='set_sizes',
            field=models.ManyToManyField(blank=True, null=True, to='shop.size'),
        ),
    ]
