# Generated by Django 4.0.3 on 2022-04-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_set_colors_product_set_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='set_colors',
            field=models.ManyToManyField(blank=True, to='shop.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='set_sizes',
            field=models.ManyToManyField(blank=True, to='shop.size'),
        ),
    ]
