# Generated by Django 4.0.3 on 2022-04-03 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_set_colors_alter_product_set_sizes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productavailability',
            options={'ordering': ['-created_at'], 'verbose_name': 'Размер продукта', 'verbose_name_plural': 'Размеры продукта'},
        ),
    ]
