# Generated by Django 4.0.3 on 2022-04-12 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='articule',
            field=models.CharField(blank=True, max_length=255, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='year',
            field=models.PositiveIntegerField(default=2021, validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(1991)], verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='have_size',
            field=models.BooleanField(default=True, verbose_name='Есть размеры'),
        ),
    ]
