# Generated by Django 4.0.3 on 2022-04-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_composition_product_model_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_code',
            field=models.PositiveIntegerField(null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_height',
            field=models.PositiveIntegerField(default=170, null=True, verbose_name='Рост модели'),
        ),
    ]
