# Generated by Django 4.0.3 on 2022-04-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_color_color_code_alter_product_model_height'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductsCollection',
        ),
    ]
