# Generated by Django 4.0.3 on 2022-04-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='Состав продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='Описание продукта'),
        ),
    ]
