# Generated by Django 4.0.3 on 2022-04-12 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_product_composition_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productavailability',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='shop.product', verbose_name='Продукт'),
        ),
    ]
