# Generated by Django 4.0.3 on 2022-04-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_bug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bug',
            new_name='Card',
        ),
    ]
