# Generated by Django 4.0.3 on 2022-04-18 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_rename_bug_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='product_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productavailability'),
        ),
    ]
