# Generated by Django 4.0.3 on 2022-04-30 13:43

from django.db import migrations, models
import shop.models.image


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_image_image_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_thumb',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=shop.models.image.thumbnail_folder),
        ),
    ]
