# Generated by Django 4.0.3 on 2022-05-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_image_image_thumb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['order'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории продуктов'},
        ),
        migrations.AddField(
            model_name='producttype',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Очередь'),
        ),
    ]
