# Generated by Django 4.0.3 on 2022-05-06 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_collection_active'),
        ('shop', '0028_alter_productavailability_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='news.collection', verbose_name='Коллекция'),
        ),
    ]
