# Generated by Django 4.0.3 on 2022-05-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_product_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['main', '-created_at'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AddField(
            model_name='image',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
