# Generated by Django 4.0.3 on 2022-05-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_image_options_image_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-main', '-created_at'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
