# Generated by Django 4.0.3 on 2022-05-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_image_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='image',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
    ]
