# Generated by Django 4.0.3 on 2022-05-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_product_active_alter_image_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Главная фотография'),
        ),
    ]
