# Generated by Django 4.0.3 on 2022-05-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_producttype_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_height',
            field=models.PositiveIntegerField(blank=True, default=170, null=True, verbose_name='Рост модели'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_size',
            field=models.PositiveIntegerField(blank=True, default=36, null=True, verbose_name='Размер модели'),
        ),
    ]
