# Generated by Django 4.0.3 on 2022-04-12 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_productavailability_product'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productavailability', verbose_name='Товар'),
        ),
    ]
