# Generated by Django 4.0.3 on 2022-05-05 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_image_image_thumb'),
        ('orders', '0005_alter_productorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='color',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.color', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='size',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.size', verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар'),
        ),
    ]
