# Generated by Django 4.0.3 on 2022-05-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
